kind: pipeline
type: docker
name: flutter-ci

# Define when this pipeline should be executed
trigger:
  branch:
    - main
  event:
    - tag

# Define the platform where your pipeline runs
platform:
  os: linux
  arch: amd64

# Define steps of the pipeline
steps:
  # Step 1: Install Flutter dependencies
  - name: install_flutter_dependencies
    image: ghcr.io/cirruslabs/flutter:3.19.1
    commands:
      - flutter pub get
      - flutter build apk --release

  - name: deploy_to_firebase
    image: node:latest
    environment:
      FIREBASE_TOKEN:
        from_secret: firebase_token
      FIREBASE_APP_ID:
        from_secret: firebase_app_id
    commands:
      - npm install -g firebase-tools
      - firebase appdistribution:distribute ./build/app/outputs/flutter-apk/app-release.apk --app $env:FIREBASE_APP_ID --token $env:FIREBASE_TOKEN
