kind: pipeline
type: docker
name: flutter-ci

# Define when this pipeline should be executed
trigger:
  branch:
    - main
  event:
    - tag

# Define the platform where your pipeline runs
platform:
  os: linux
  arch: amd64

# Define steps of the pipeline
steps:
  # Step 1: Install Flutter dependencies
  - name: install_flutter_dependencies
    image: cirrusci/flutter:3.19.0
    commands:
      - flutter pub get
      - flutter build apk --release