kind: pipeline
name: flutter-ci

# Define when this pipeline should be executed
trigger:
  event:
    - tag
  ref:
    - refs/tags/v\d+\.\d+\.\d+-beta

# Define the platform where your pipeline runs
platform:
  os: linux
  arch: amd64

# Define steps of the pipeline
steps:
  # Step 1: Clone the repository
  - name: clone
    image: alpine/git
    commands:
      - git clone ssh://git@github.com:andikadeveloper/flutter_drone_ci.git
      - cd mytok

  # Step 2: Install Flutter dependencies
  - name: install_flutter_dependencies
    image: cirrusci/flutter:stable
    commands:
      - flutter pub get

  # Step 3: Build Android app
  - name: build_app
    image: cirrusci/flutter:stable
    commands:
      - flutter build apk --release
